package homework3;

// import homework1.Account.*;
public class TestClass4 {
    public static void main(String []args)
    {
        // Account[] all_account=new Account[100000];
        // int counter=0;
        // for(int i=0;i<100000;i++)
        // {
        //     all_account[i]=new Account(Integer.toString(++counter), "null", null, counter);
        // }
        // all_account[0].login();
        // long lazy_start=System.nanoTime();
        // for(int i=1;i<100000;i++)
        //     all_account[0].new_following(all_account[i]);
        
        // for(int i=1;i<100000;i++)
        //     all_account[0].delete_following(all_account[i]);
        
        // // long start_time1=System.nanoTime();
        // long lazy_finish=System.nanoTime();
        // long totalTime_lazy = lazy_finish - lazy_start;
        // System.out.println( "\n\ntested element number equals 100000:"+"\u001B[32m"+totalTime_lazy/1e9+"\u001B[0m\n\n");
        // all_account[0].logout();
        long start_time1=System.nanoTime();

        System.out.println("SCENARIO 1\n");
        System.out.println("Step 1... Creating accounts...\nAn account with username gizemsungu has been created.\nAn account with username sibelgulmez has been created.\nAn account with username gokhankaya has been created.\n\n");
        System.out.println("An account with username 1 has been created.");
        System.out.println("An account with username 2 has been created.");
        System.out.println("An account with username 3 has been created.");
        System.out.println("An account with username 4 has been created.");
        System.out.println("An account with username 5 has been created.");
        System.out.println("An account with username 6 has been created.");
        System.out.println("An account with username 7 has been created.");
        Account account1=new Account("gizemsungu", "van", "10.03.2001",0);
        Account account2=new Account("sibelgulmez", "bitlis", "10.03.2002",1);
        Account account3=new Account("gokhankaya", "adana", "10.03.2003",2);
        Account account4=new Account("user1", "adana", "10.03.2003",2);
        Account account5=new Account("user2", "adana", "10.03.2003",2);
        Account account6=new Account("user3", "adana", "10.03.2003",2);
        Account account7=new Account("user4", "adana", "10.03.2003",2);
        Account account8=new Account("user5", "adana", "10.03.2003",2);
        Account account9=new Account("user6", "adana", "10.03.2003",2);
        Account account10=new Account("user7", "adana", "10.03.2003",2);
        System.out.println("Step 2... Logging into an account (username: sibelgulmez)...\n");
        account2.login();
        System.out.println("Step 3... Sharing two post...\n");
        account2.new_post(new Post("sibelgulmez", 0, 1, "WORK HARD"));
        account2.new_post(new Post("sibelgulmez", 1, 1, "WORK too HARD"));
        System.out.println("--> \"gokhankaya\" share post(programe give error message)\n");
        account3.new_post(new Post("gokhankaya", 0, 3, "new post"));
        System.out.println("Step 4... Following gizemsungu and gokhankaya...\n");
        account2.new_following(account1);
        account2.new_following(account3);
        System.out.println("Step 5... Logging out from account 'sibelgulmez'...\n");
        account2.logout();
        System.out.println("Step 6... Logging into another account (username: gokhankaya)\n");
        account3.login();
        System.out.println("Step 7... Viewing sibelgulmez's profile...\n");
        account3.visit_profile(account2);
        System.out.println("Step 8... Viewing sibelgulmez'posts...\n");
        account3.get_post_information(account2);
        System.out.println("Step 9... Liking a post of sibelgulmez...\n");
        account3.like_post(account2, 0);
        System.out.println("Step 10... Adding a comment on a post of sibelgulmez...\n");
        account3.add_comment(account2, 0, "java nice data easy");
        System.out.println("-->\"gokhankaya\" send message to \"sibelgulmez\" (program give error message)\n");
        account3.add_outboux(account2, new Message("sibelgulmez", "gokhankaya", "java easy", 0));
        System.out.println("Step 11... Following sibelgulmez and gizemsungu...        \n");
        account3.new_following(account2);
        account3.new_following(account1);
        System.out.println("Step 12... Sending a message to gizemsungu...\n");
        account3.add_outboux(account1,new Message("gizemsungu", "gokhankaya", "slm", 0) );
        System.out.println("Step 13... Logging out from account 'gokhankaya'..        \n");
        account3.logout();
        System.out.println("Step 14... Logging into another account (username: gizemsungu)       \n");
        account1.login();
        System.out.println("Step 15... Checking outbox...        \n");
        System.out.println("There is/are "+account1.get_outbox_number()+" message in outbox");
        System.out.println("-->\"gokhankaya\"  view  \"sibelgulmez\" post(programe give error message)\n");
        account3.visit_profile(account2);
        System.out.println("Step 16... Checking inbox...        \n");
        System.out.println("There is/are "+account1.get_inbox_number()+" message in outbox");
        System.out.println("Step 17... Viewing inbox...\n");
        System.out.println(account1.get_In_messages());
        System.out.println("Step 18... Viewing sibelgulmez's profile...        \n");
        account1.visit_profile(account2);
        System.out.println("Step 19... Viewing sibelgulmez's posts...\n");
        account1.get_post_information(account2);
        System.out.println("Step 20... Viewing sibelgulmez's posts' interactions...        \n");
        account1.get_interaction_information(account2);
        System.out.println("Step 21... Liking sibelgulmez's posts...\n");
        account1.like_post(account2, 0);
        System.out.println("Step 22... Viewing sibelgulmez's posts' interactions..\n");
        account1.get_interaction_information(account2);
        account1.logout();
        long finish_time1=System.nanoTime();
        long totalTime1 = finish_time1 - start_time1;
        // System.out.println( "\u001B[32m"+totalTime1/1e9+"\u001B[0m");


        Long start_time2=System.nanoTime();
        System.out.println("\n\n\nSCENARIO 2\n");
        System.out.println("1. \"gizemsungu\" logs in.        \n");
        account1.login();
        System.out.println("\ta. shares a post (let's call it Post1).        \n");
        account1.new_post(new Post("gizemsungu", 0, 0, "post1"));
        System.out.println("\tb. shares another post (let's call it Post2).\n");
        account1.new_post(new Post("gizemsungu", 1, 0, "post2"));
        System.out.println("\tc. logs out.\n");
        account1.logout();
        System.out.println("2. \"sibelgulmez\" logs in.\n");
        account2.login();
        System.out.println("\ta. views the profile of \"gizemsungu\".\n");
        account2.visit_profile(account1);
        System.out.println("\tb. likes Post1.\n");
        account2.like_post(account1, 0);
        System.out.println("\tc. log out.\n");
        account2.logout();
        System.out.println("3. \"gokhankaya\" logs in.\n");
        account3.login();
        System.out.println("\ta. views the profile of \"gizemsungu\".\n");
        account3.visit_profile(account1);
        System.out.println("\tb. comments on Post2.\n");
        account3.add_comment(account1, 1, "NICE:)");
        System.out.println("\tc. sends a message to \"gizemsungu\"\n");
        account3.add_outboux(account1,new Message("gizemsungu", "gokhankaya", "Hello!", 1));
        System.out.println("\td. log out.\n");
        account3.logout();
        System.out.println("1. \"gizemsungu\" logs in.        \n");
        account1.login();
        System.out.println("\ta. views her own profile.\n");
        account1.visit_profile(account1);
        System.out.println("\tb. reads the message from \"gokhankaya\"\n");
        System.out.println(account1.get_In_messages("gokhankaya"));
        long finish_time2=System.nanoTime();
        long totalTime2 = (finish_time2 - start_time2);
        // System.out.println( "\u001B[32m"+totalTime1/1e9+"\u001B[0m");

        long start_time3=System.nanoTime();
        System.out.println("\n\n\nSCENARIO 3\n");
        System.out.println("1. \"gizemsungu\" logs in.        \n");
        account1.login();
        System.out.println("\ta.blocks \"sibelgulmez\". \n");
        account1.add_ban(account2);
        System.out.println("\tb. logs out.\n");
        account1.logout();
        System.out.println("2. \"sibelgulmez\" logs in.\n");
        account2.login();
        System.out.println("\ta. tries to view the profile of \"gizemsungu\".\n");
        account2.visit_profile(account1);
        System.out.println("\tb. tries to send a message to \"gizemsungu\".\n");
        account2.add_outboux(account1,new Message("gizemsungu", "sibelgulmez", "HI!!", 2));
        System.out.println("\tc. logs out.\n");
        account2.logout();
        System.out.println("3. \"gizemsungu\" logs in.        \n");
        account1.login();
        System.out.println("\ta. \"sibelgulmez\" remove \"gizemsungu\" from blocked account list\n");
        account1.delete_ban(account2);
        System.out.println("\tb. logs out.\n");
        account1.logout();
        System.out.println("4. \"sibelgulmez\" logs in.\n");
        account2.login();
        System.out.println("\ta. tries to view the profile of \"gizemsungu\".\n");
        account2.visit_profile(account1);
        System.out.println("\tb. tries to send a message to \"gizemsungu\".(CONTENT:HI!!)\n");
        account2.add_outboux(account1,new Message("gizemsungu", "sibelgulmez", "HI!!", 2));
        System.out.println("\n");
        account2.logout();
        account1.login();
        System.out.println("\n\ngizemsungu's inbox\n\n");
        System.out.println(account1.get_In_messages());
        account1.logout();
        long finish_time3=System.nanoTime();
        long totalTime3 = finish_time3 - start_time3;
        // System.out.println( "\u001B[32m"+totalTime3/1e9+"\u001B[0m");

        long start_time4=System.nanoTime();
        System.out.println("\n\n\nSCENARIO 4\n");
        System.out.println("1-gokhankaya login\n");
        account3.login();
        System.out.println("\nCHECKED UNFOLLOW METHOD\n");
        
        System.out.println("follow account that username is user1\n");
        System.out.println("follow account that username is user2\n");
        System.out.println("follow account that username is user3\n");
        System.out.println("follow account that username is user4\n");
        System.out.println("follow account that username is user5\n");
        System.out.println("follow account that username is user6\n");
        System.out.println("follow account that username is user7\n");
        account3.new_following(account4);
        account3.new_following(account5);
        account3.new_following(account6);
        account3.new_following(account7);
        account3.new_following(account8);
        account3.new_following(account9);
        account3.new_following(account10);
        System.out.println("view gokhankaya profile");
        account3.visit_profile(account3);
        System.out.println("Unfollow user1");
        account3.delete_following(account4);
        System.out.println("Unfollow user2");
        account3.delete_following(account5);
        System.out.println("Unfollow user3");
        account3.delete_following(account6);
        System.out.println("view gokhankaya profile");
        account3.visit_profile(account3);

        System.out.println("\nCHECKED UNCOMMENT AND UNLIKE METHOD\n");
        System.out.println("show sibelgulmez interaction\n");
        account3.get_interaction_information(account2);
        System.out.println("uncomment sibelgulmez post\n");
        account3.delete_comment(account2, 0, "java nice data easy");
        System.out.println("unlike sibelgulmez post\n");
        account3.delete_like(account2, 0);
        System.out.println("show sibelgulmez interaction\n");
        account3.get_interaction_information(account2);
        System.out.println("share 1 post\n");
        account3.new_post(new Post("gokhankaya", 0, 3, "This homework is hard"));
        System.out.println("gokhankaya logout\n");
        account3.logout();
        System.out.println("2-sibelgulmez login\n");
        account2.login();
        System.out.println("\nCHECKED STORY METHOD\n");
        System.out.println("send message gizemsungu\n");
        account2.add_outboux(account3, new Message("gizemsungu", "sibelgulmez","where are you", 0));
        System.out.println("show stroy\n");
        System.out.println(account2.getHistory());
        System.out.println("Visit sibelgulmez profile\n");
        account2.visit_profile(account2);
        System.out.println("unfollow gokhan\n");
        account2.delete_following(account3);
        System.out.println("Visit sibelgulmez profile\n");
        account2.visit_profile(account2);
        System.out.println("unfollow gizemsungu\n");
        account2.delete_following(account1);
        System.out.println("show stroy\n");
        System.out.println(account2.getHistory());
        System.out.println("logout\n");
        account2.logout();
        
        System.out.println("\nTHIS PART IS SAME AS SCENARIO 3. I HAVE CHECKED UNBLOCK METHOD FEATURES.BUT I HAVE DISPLAYED AGAIN\n\n");
        System.out.println("1.sibelgulmez login\n");
        account2.login();
        System.out.println("follow gizemsungu\n");
        account2.new_following(account1);
        System.out.println("visit herself profile\n");
        account2.visit_profile(account2);
        System.out.println("sibelgulmez logout\n");
        account2.logout();
        System.out.println("2. \"gizemsungu\" logs in.        \n");
        account1.login();
        System.out.println("visit herself profile\n");
        account1.visit_profile(account1);
        System.out.println("\ta.blocks \"sibelgulmez\". \n");
        account1.add_ban(account2);
        System.out.println("visit herself profile\n");
        account1.visit_profile(account1);
        System.out.println("visit sibelgulmez profile\n");
        account1.visit_profile(account2);
        System.out.println("\tb. logs out.\n");
        account1.logout();
        System.out.println("3. \"sibelgulmez\" logs in.\n");
        account2.login();
        System.out.println("\ta. tries to view the profile of \"gizemsungu\".\n");
        account2.visit_profile(account1);
        System.out.println("\tb. tries to send a message to \"gizemsungu\".\n");
        account2.add_outboux(account1,new Message("gizemsungu", "sibelgulmez", "HI!!", 2));
        System.out.println("\tc. logs out.\n");
        account2.logout();
        System.out.println("4. \"gizemsungu\" logs in.        \n");
        account1.login();
        System.out.println("\ta. \"sibelgulmez\" remove \"gizemsungu\" from blocked account list\n");
        account1.delete_ban(account2);
        System.out.println("\tb. logs out.\n");
        account1.logout();
        System.out.println("5. \"sibelgulmez\" logs in.\n");
        account2.login();
        System.out.println("\ta. tries to view the profile of \"gizemsungu\".\n");
        account2.visit_profile(account1);
        System.out.println("\tb. tries to send a message to \"gizemsungu\".(CONTENT:HI!!)\n");
        account2.add_outboux(account1,new Message("gizemsungu", "sibelgulmez", "HI!!", 2));
        System.out.println("\n");
        account2.logout();
        account1.login();
        System.out.println("\n\ngizemsungu's inbox\n\n");
        System.out.println(account1.get_In_messages());
        account1.logout();
        long finish_time4=System.nanoTime();
        long totalTime4 = finish_time4 - start_time4;
        System.out.println( "Test Scenario 1 :"+"\u001B[32m"+totalTime1/1e9+"\u001B[0m");
        System.out.println( "Test Scenario 2 :"+"\u001B[32m"+totalTime2/1e9+"\u001B[0m");
        System.out.println( "Test Scenario 3 :"+"\u001B[32m"+totalTime3/1e9+"\u001B[0m");
        System.out.println( "Test Scenario 4 :"+"\u001B[32m"+totalTime4/1e9+"\u001B[0m");
    }
}
